### PR TITLE
refactor: moved code to development branch

### PR DESCRIPTION
**Pull request by sjsouvik**
Added all code files to development branch

### CODE REVIEW

**Review by Aravindan07 — CHANGES_REQUESTED** [review]
1. Place the close icon for the alert in the center
2. Add hover effects to button.
3. Fix the contrast issues in notification component.
4. Change the cursor to pinter in cards social links.
5. add hover effects to navigation component
6. Fix the navbar and sidebar

**Comment by vinaybajjuri58** [comment]
Hey Souvik
The component library is good
I would like to suggest some changes 
-proper placement of component on click(Heading is not visible)
-Try adding some more lists like numbered lists 
-Try removing the installation tab in left navbar as you already have logo and top arrow icon right-side of the page

**Review by vinaybajjuri58 — COMMENTED** [review]
Hey Souvik
The component library is good
I would like to suggest some changes
-proper placement of component on click(Heading is not visible)
-Try adding some more lists like numbered lists
-Try removing the installation tab in left navbar as you already have logo and top arrow icon right-side of the page

**Comment by khusharth** [comment]
- Need to add Favicon
- For **Buttons with badge** you can shift from grey to red for badge color.
- Remove the secondary button.
- In Modal for continue you can use the primary button.
- For textArea component: Add fontSize.
- Navigation: Change button color to white with primary color text.
- Ui suggestion: Alert: Check the contrast of yellow alert.
- Instead of doing `https://ui-blocks.netlify.app/style.css` you should do `https://ui-blocks.netlify.app/ui-block.css`
- (To do later): Add Js for Toast.
- Make documentation site mobile responsive https://uiblocks-d.netlify.app/ (sidebar)

**Pull request merged**
